---
- name: install gh
  tags: gh
  vars:
    asdf_user: "{{ ansible_user }}"
    asdf_group: "{{ ansible_user }}"
    asdf_plugins:
      - name: github-cli
        repository:  https://github.com/bartlomiejdanek/asdf-github-cli.git
        versions:
          - 2.16.1
        global: 2.16.1
  include_role:
    name: cimon-io.asdf
