---
- name: download gh bin
  tags: gh
  get_url: url=https://github.com/cli/cli/releases/download/v2.16.0/gh_2.16.0_linux_amd64.tar.gz dest=/tmp/gh.tar.gz

- name: extract gh bin
  tags: gh
  unarchive:
    src: /tmp/gh.tar.gz
    dest: /tmp
    remote_src: yes

- name: install gh bin
  tags: gh
  shell: "mv /tmp/gh_2.16.0_linux_amd64/bin/gh {{ ansible_env.HOME }}/bin/gh"

- name: set gh permission
  tags: gh
  file:
    path: "{{ ansible_env.HOME }}/bin/gh"
    mode: 'u=rx,g=rx,o=r'
