---
- name: install deno
  tags: deno
  vars:
    asdf_user: "{{ ansible_user }}"
    asdf_group: "{{ ansible_user }}"
    asdf_plugin_dependencies:
      - curl
      - git
      - unzip
    asdf_plugins:
      - name: deno
        repository:  https://github.com/asdf-community/asdf-deno.git
        versions:
          - 1.26.0
        global: 1.26.0
  include_role:
    name: cimon-io.asdf
