---
- name: install deno deps
  tags: deno
  become: yes
  apt:
    pkg:
      - curl
    state: present
    update_cache: yes
    autoclean: yes
    autoremove: yes

- name: install deno
  tags: deno
  shell: curl -sSL https://deno.land/x/install/install.sh | bash
  args:
    creates: "{{ ansible_env.HOME }}/.deno/bin/deno" # run if file not exist

- name: install deno autocompletion
  tags: deno
  become: yes
  shell: "{{ ansible_env.HOME }}/.deno/bin/deno completions bash > /etc/bash_completion.d/deno"
  args:
    creates: /etc/bash_completion.d/deno # run if file not exist
