---
- name: create desktop scripts dir
  tags: desktop_scripts
  file:
    path: "/home/{{ ansible_user }}/scripts"
    state: directory

- name: copy desktop scripts
  tags: desktop_scripts
  copy:
    src: "{{ item }}"
    dest: "/home/{{ ansible_user }}/scripts/{{ item }}"
    mode: '0744'
  with_items:
    - focus-terminal.sh
    - git-standup.sh
