---
- name: create app dir
  tags: user_apps
  file:
    path: "{{ ansible_env.HOME }}/app"
    state: directory

- name: create bin dir
  tags: user_apps
  file:
    path: "{{ ansible_env.HOME }}/bin"
    state: directory

- name: install user apps
  tags: user_apps
  become: yes
  apt:
    pkg:
      - curl
      - ffmpeg
      - git-extras
      - htop
      - jq
      - openssl
      - shellcheck
      - sqlite3
      - tar
      - tree
      - unzip
      - wget
      - wmctrl
      - xclip
    state: present
    update_cache: yes
    autoclean: yes
    autoremove: yes
