---
- name: install git
  tags: git
  become: yes
  apt:
    pkg:
      - git
    state: present
    update_cache: yes
    autoclean: yes
    autoremove: yes

- name: copy .gitignore
  tags: git
  copy:
    src: .gitignore
    dest: "{{ ansible_env.HOME }}/.gitignore"
    mode: '0644'

- name: copy .gitconfig
  tags: git
  copy:
    src: .gitconfig
    dest: "{{ ansible_env.HOME }}/.gitconfig"
    mode: '0644'
