---
- name: create ssh dir
  file:
    path: "/home/{{ ansible_user }}/.ssh"
    state: directory

- name: install ssh
  tags: ssh
  become: yes
  apt:
    pkg:
      - ssh
    state: present
    update_cache: yes
    autoclean: yes
    autoremove: yes

- name: copy ssh config
  tags: ssh
  copy:
    src: config
    dest: "/home/{{ ansible_user }}/.ssh/config"
    mode: '0644'
