---
- name: install fzf
  tags: fzf
  git:
    repo: https://github.com/junegunn/fzf.git
    dest: "/home/{{ ansible_user }}/.fzf"
    depth: 1

- name: configure fzf
  tags: fzf
  shell: "/home/{{ ansible_user }}/.fzf/install --key-bindings --completion --no-update-rc"
