---
- name: install vim
  tags: vim
  become: yes
  apt:
    pkg:
      - vim
    state: present
    update_cache: yes
    autoclean: yes
    autoremove: yes

- name: copy .vimrc
  tags: vim
  copy:
    src: .vimrc
    dest: "/home/{{ ansible_user }}/.vimrc"
    mode: '0644'
