---
- name: install desktop
  tags: desktop
  become: yes
  apt:
    pkg:
      - chrome-gnome-shell
      - gdm3
      - gnome-core
      - xfonts-base
      - xserver-xorg
    state: present
    update_cache: yes
    autoclean: yes
    autoremove: yes

- name: add theme deb
  tags: desktop
  become: yes
  apt_repository:
    repo: ppa:alessandro-strada/ppa
    state: present

- name: install theme
  tags: desktop
  become: yes
  apt:
    pkg:
      - arc-theme
    state: present
    update_cache: yes
    autoclean: yes
    autoremove: yes
