---
- name: install docker deps
  tags:
    - docker
    - docker-compose
  become: yes
  apt:
    pkg:
      - curl
    state: present
    update_cache: yes
    autoclean: yes
    autoremove: yes

- name: install docker
  tags: docker
  become: yes
  shell: curl -sSL https://get.docker.com | bash
  args:
    creates: /usr/bin/docker # run if file not exist

- name: add user to docker group
  tags: docker
  become: yes
  shell: usermod -aG docker $(whoami) # whoami = romainprignon

- name: install docker-compose
  tags: docker-compose
  get_url:
    url: https://github.com/docker/compose/releases/download/1.27.3/docker-compose-Linux-x86_64
    dest: "{{ ansible_env.HOME }}/apps/docker-compose"
    mode: 'u=rx,g=rx,o=r'
