---
- name: install node
  tags: node
  vars:
    asdf_user: "{{ ansible_user }}"
    asdf_group: "{{ ansible_user }}"
    asdf_plugin_dependencies:
      - dirmngr
      - gpg
      - curl
      - gawk
    asdf_plugins:
      - name: node
        repository:  https://github.com/asdf-vm/asdf-nodejs.git
        versions:
          - 16.17.1
          - latest
        global: 16.17.1
  include_role:
    name: cimon-io.asdf

- name: copy npm config
  tags: node
  copy:
    src: .npmrc
    dest: "/home/{{ ansible_user }}/.npmrc"
    mode: '0644'
