---
- name: install latest node
  tags: node
  become: yes
  shell: "/home/{{ ansible_user }}/bin/n latest"

- name: install lts node
  tags: node
  become: yes
  shell: "/home/{{ ansible_user }}/bin/n lts"

- name: install autocompletion
  tags: node
  become: yes
  shell:  npm completion > /etc/bash_completion.d/npm
  args:
    creates: /etc/bash_completion.d/npm # run if file not exist

- name: copy npm config
  tags: node
  copy:
    src: .npmrc
    dest: "/home/{{ ansible_user }}/.npmrc"
    mode: '0644'

- name: install npm global deps
  tags: node
  become: yes
  shell: >
    npm install -g \
      @babel/node \
      cdktf-cli \
      depcheck \
      git-split-diffs \
      gitmoji-cli \
      hotel \
      http-server \
      pkgcount \
      thanks \
      ts-node \
      types-checker \
      typescript \
      zx
