---
- name: create vscode config dir
  tags: vscode
  file:
    path: "{{ ansible_env.HOME }}/.config/Code/User"
    state: directory

- name: fetch vscode app
  tags: vscode
  get_url: url=https://update.code.visualstudio.com/1.49.1/linux-deb-x64/stable dest=/tmp/

- name: install vscode app
  tags: vscode
  become: yes
  apt:
    deb: /tmp/code_1.49.1-1600299189_amd64.deb
    update_cache: yes
    autoclean: yes
    autoremove: yes

- name: install vscode extension
  tags: vscode
  shell: "code --install-extension {{ item }}"
  with_items:
    - christian-kohler.path-intellisense
    - dbaeumer.vscode-eslint
    - devtanc.tab-hero
    - eamodio.gitlens
    - EditorConfig.EditorConfig
    - eg2.vscode-npm-script
    - felixfbecker.php-debug
    - felixfbecker.php-intellisense
    - formulahendry.auto-close-tag
    - geddski.macros
    - ikappas.phpcs
    - mikestead.dotenv
    - ms-azuretools.vscode-docker
    - ms-python.python
    - ms-vscode.typescript-javascript-grammar
    - ms-vscode.vscode-typescript-tslint-plugin
    - msjsdiag.debugger-for-chrome
    - PKief.material-icon-theme
    - yatki.vscode-surround

- name: copy vscode config
  tags: vscode
  copy:
    src: "{{ item }}"
    dest: "{{ ansible_env.HOME }}/.config/Code/User/{{ item }}"
    mode: '0644'
  with_items:
    - settings.json
    - keybindings.json
