---
- name: create desktop scripts dir
  tags: desktop_scripts
  file:
    path: "{{ ansible_env.HOME }}/scripts"
    state: directory

- name: copy desktop scripts
  tags: desktop_scripts
  copy:
    src: "{{ item }}"
    dest: "{{ ansible_env.HOME }}/scripts/{{ item }}"
    mode: '0644'
  with_items:
    - focus-terminal.sh
    - git-standup.sh
