---
- name: install fzf
  tags: fzf
  git:
    repo: https://github.com/junegunn/fzf.git
    dest: "{{ ansible_env.HOME }}/.fzf"
    depth: 1

- name: configure fzf
  tags: fzf
  shell: "{{ ansible_env.HOME }}/.fzf/install --key-bindings --completion --no-update-rc"
