---
- name: install python deps # because asdf_plugin_dependencies do not work ??
  tags: python
  become: yes
  apt:
    pkg:
      - build-essential
      - curl
      - llvm
      - make
      - wget
      - zlib1g-dev
      - xz-utils
      - tk-dev
      - libxml2-dev
      - libxmlsec1-dev
      - liblzma-dev
      - libffi-dev
      - libssl-dev
      - libbz2-dev
      - libreadline-dev
      - libsqlite3-dev
      - libncursesw5-dev
    state: present
    update_cache: yes
    autoclean: yes
    autoremove: yes

- name: install python
  tags: python
  vars:
    asdf_user: "{{ ansible_user }}"
    asdf_group: "{{ ansible_user }}"
    asdf_plugins:
      - name: python
        repository:  https://github.com/asdf-community/asdf-python.git
        versions:
          - 3.8.2
        global: 3.8.2
  include_role:
    name: cimon-io.asdf

- name: install poetry
  tags: python
  vars:
    asdf_user: "{{ ansible_user }}"
    asdf_group: "{{ ansible_user }}"
    asdf_plugins:
      - name: poetry
        repository:  https://github.com/asdf-community/asdf-poetry.git
        versions:
          - 1.2.1
        global: 1.2.1
  include_role:
    name: cimon-io.asdf
