---
- name: install python deps
  tags: python
  become: yes
  apt:
    pkg:
      - curl
      - git
      - zlib1g-dev
      - libffi-dev
      - libbz2-dev
      - libreadline-dev
      - libssl-dev
      - libsqlite3-dev
    state: present
    update_cache: yes
    autoclean: yes
    autoremove: yes

- name: install python
  tags: python
  shell: curl -sSL https://pyenv.run | bash
  args:
    creates: "{{ ansible_env.HOME }}/.pyenv/bin/pyenv" # run if file not exist

- name: install poetry deps
  tags: python
  become: yes
  apt:
    pkg:
      - python3-pip
      - python3-venv
    state: present
    update_cache: yes
    autoclean: yes
    autoremove: yes

- name: configure python alternative
  tags: python
  become: yes
  community.general.alternatives:
    name: python
    link: /usr/bin/python
    path: /usr/bin/python3

- name: configure pip alternative
  tags: python
  become: yes
  community.general.alternatives:
    name: pip
    link: /usr/bin/pip
    path: /usr/bin/pip3

- name: download poetry
  tags: python
  get_url:
    url: https://install.python-poetry.org
    dest: /tmp/install-poetry.py

- name: install poetry
  tags: python
  command: python3 /tmp/install-poetry.py

- name: install python global deps
  tags: python
  shell: >
    pip install \
      git-machete
      zxpy
