---
- name: install fonts
  tags: fonts
  become: yes
  apt:
    pkg:
      - font-manager
      - fonts-droid-fallback
      - fonts-inconsolata
      - fonts-liberation
      - ttf-dejavu
      - ttf-ancient-fonts
      - ttf-ubuntu-font-family
    state: present
    update_cache: yes
    autoclean: yes
    autoremove: yes
