---
- name: create micro config dir
  tags: micro
  file:
    path: "/home/{{ ansible_user }}/.config/micro"
    state: directory

- name: install micro
  tags: micro
  vars:
    asdf_user: "{{ ansible_user }}"
    asdf_group: "{{ ansible_user }}"
    asdf_plugins:
      - name: micro
        repository:  https://github.com/YR-ZR0/asdf-micro.git
        versions:
          - 2.0.4
        global: 2.0.4
  include_role:
    name: cimon-io.asdf

- name: copy micro config
  tags: micro
  copy:
    src: settings.json
    dest: "/home/{{ ansible_user }}/.config/micro/settings.json"
    mode: '0644'
