---
- name: create micro config dir
  tags: micro
  file:
    path: "/home/{{ ansible_user }}/.config/micro"
    state: directory

- name: install micro deps
  tags: micro
  become: yes
  apt:
    pkg:
      - curl
    state: present
    update_cache: yes
    autoclean: yes
    autoremove: yes

- name: install micro
  tags: micro
  shell: curl -sSL https://getmic.ro | bash
  args:
    chdir: "/home/{{ ansible_user }}/bin"
    creates: "/home/{{ ansible_user }}/bin/micro" # run if file not exist

- name: copy micro config
  tags: micro
  copy:
    src: settings.json
    dest: "/home/{{ ansible_user }}/.config/micro/settings.json"
    mode: '0644'
