---
- name: create rc dir
  tags: rc
  file:
    path: "/home/{{ ansible_user }}/.rc"
    state: directory

- name: copy common rc
  tags: rc
  copy:
    src: common.rc
    dest: "/home/{{ ansible_user }}/.rc/common.rc"
    mode: '0644'
