---
- name: install latest node
  tags: node
  become: yes
  shell: "{{ ansible_env.HOME }}/bin/n latest"

- name: install lts node
  tags: node
  become: yes
  shell: "{{ ansible_env.HOME }}/bin/n lts"

- name: install autocompletion
  tags: node
  become: yes
  shell:  npm completion > /etc/bash_completion.d/npm
  args:
    creates: /etc/bash_completion.d/npm # run if file not exist

- name: copy npm config
  tags: node
  copy:
    src: .npmrc
    dest: "{{ ansible_env.HOME }}/.npmrc"
    mode: '0644'
