---
- name: download jetbrain app
  tags: jetbrain
  get_url: url=https://download.jetbrains.com/toolbox/jetbrains-toolbox-1.26.0.13072.tar.gz dest=/tmp/jetbrains-toolbox.tar.gz

- name: extract jetbrain app
  tags: jetbrain
  unarchive:
    src: /tmp/jetbrains-toolbox.tar.gz
    dest: /tmp
    remote_src: yes

- name: install jetbrain app
  tags: jetbrain
  shell: "mv /tmp/jetbrains-toolbox-1.26.0.13072/jetbrains-toolbox /home/{{ ansible_user }}/app/jetbrains-toolbox"

- name: set jetbrain permission
  tags: jetbrain
  file:
    path: "/home/{{ ansible_user }}/app/jetbrains-toolbox"
    mode: 'u=rx,g=rx,o=r'
