---
- name: create .zsh dir
  tags: zsh
  file:
    path: "/home/{{ ansible_user }}/.zsh"
    state: directory

- name: install zsh deps
  tags: zsh
  become: yes
  apt:
    pkg:
      - git
    state: present
    update_cache: yes
    autoclean: yes
    autoremove: yes

- name: install zsh
  tags: zsh
  become: yes
  apt:
    pkg:
      - zsh
    state: present
    update_cache: yes
    autoclean: yes
    autoremove: yes

- name: install zsh plugins zsh-autosuggestions
  tags: zsh
  git:
    depth: 1
    repo: https://github.com/zsh-users/zsh-autosuggestions.git
    dest: "/home/{{ ansible_user }}/.zsh/zsh-autosuggestions"

- name: install zsh plugins zsh-syntax-highlighting
  tags: zsh
  git:
    depth: 1
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest: "/home/{{ ansible_user }}/.zsh/zsh-syntax-highlighting"

- name: install zsh plugins zsh-git-prompt
  tags: zsh
  git:
    depth: 1
    repo: https://github.com/olivierverdier/zsh-git-prompt.git
    dest: "/home/{{ ansible_user }}/.zsh/zsh-git-prompt"

- name: install zsh plugins zsh-history-substring-search
  tags: zsh
  git:
    depth: 1
    repo: https://github.com/zsh-users/zsh-history-substring-search.git
    dest: "/home/{{ ansible_user }}/.zsh/zsh-history-substring-search"

- name: install zsh plugins fzf-tab
  tags: zsh
  git:
    depth: 1
    repo: https://github.com/Aloxaf/fzf-tab
    dest: "/home/{{ ansible_user }}/.zsh/fzf-tab"

- name: copy .zprofile
  tags: zsh
  copy:
    src: .zprofile
    dest: "/home/{{ ansible_user }}/.zprofile"
    mode: '0644'

- name: copy .zshrc
  tags: zsh
  copy:
    src: .zshrc
    dest: "/home/{{ ansible_user }}/.zshrc"
    mode: '0644'

- name: copy gitstatus.py
  tags: zsh
  copy:
    src: gitstatus.py
    dest: "/home/{{ ansible_user }}/.zsh/zsh-git-prompt/gitstatus.py"
    mode: '0644'

- name: copy zsh-git-prompt.sh
  tags: zsh
  copy:
    src: zsh-git-prompt.sh
    dest: "/home/{{ ansible_user }}/.zsh/zsh-git-prompt/zshrc.sh"
    mode: '0644'
