---
- name: install prompt deps
  tags: prompt
  become: yes
  apt:
    pkg:
      - git
    state: present
    update_cache: yes
    autoclean: yes
    autoremove: yes

- name: install prompt
  tags: prompt
  git:
    repo: https://github.com/magicmonty/bash-git-prompt.git
    dest: "{{ ansible_env.HOME }}/.bash-git-prompt"

- name: copy .aliases
  tags: prompt
  copy:
    src: .aliases
    dest: "{{ ansible_env.HOME }}/.aliases"
    mode: '0644'

- name: copy .bashrc
  tags: prompt
  copy:
    src: .bashrc
    dest: "{{ ansible_env.HOME }}/.bashrc"
    mode: '0644'

- name: copy .exports
  tags: prompt
  copy:
    src: .exports
    dest: "{{ ansible_env.HOME }}/.exports"
    mode: '0644'

- name: copy .functions
  tags: prompt
  copy:
    src: .functions
    dest: "{{ ansible_env.HOME }}/.functions"
    mode: '0644'

- name: copy .inputrc
  tags: prompt
  copy:
    src: .inputrc
    dest: "{{ ansible_env.HOME }}/.inputrc"
    mode: '0644'

- name: copy .profile
  tags: prompt
  copy:
    src: .profile
    dest: "{{ ansible_env.HOME }}/.profile"
    mode: '0644'

- name: copy Single_line_Ubuntu_Romain.bgptheme
  tags: prompt
  copy:
    src: Single_line_Ubuntu_Romain.bgptheme
    dest: "{{ ansible_env.HOME }}/.bash-git-prompt/themes/Single_line_Ubuntu_Romain.bgptheme"
    mode: '0644'
