---
- name: create rc dir
  tags: rc
  file:
    path: "{{ ansible_env.HOME }}/.rc"
    state: directory

- name: copy common rc
  tags: rc
  copy:
    src: common.rc
    dest: "{{ ansible_env.HOME }}/.rc/common.rc"
    mode: '0644'
