---
- name: install packer
  tags: packer
  vars:
    asdf_user: "{{ ansible_user }}"
    asdf_group: "{{ ansible_user }}"
    asdf_plugins:
      - name: packer
        repository:  https://github.com/asdf-community/asdf-hashicorp.git
        versions:
          - 1.8.3
        global: 1.8.3
  include_role:
    name: cimon-io.asdf
