---
- name: desktop
  hosts: default

  roles:
    - role: desktop
    - role: gtk
    - role: desktop_apps
    - role: desktop_scripts
    - role: vscode
    - role: subl
    - role: jetbrain
    - role: hyper
    - role: doc
