---
- name: runtime
  hosts: default

  # - role: multipass
  roles:
    - role: ansible
    - role: docker
    - role: packer
    - role: node
    - role: deno
    - role: python
    - role: php
    - role: terraform
