---
- name: system
  hosts: default
  roles:
    - role: system_apps
    - role: user_apps
    - role: micro # when there is config
    - role: ssh # when there is config
    - role: git # when there is config
    - role: vim # when there is config
    - role: n # when there is config
