---
- name: system
  hosts: default
  roles:
    - role: system
    - role: system_apps
    - role: locales
    - role: user_apps
    - role: micro # when there is config
    - role: ssh # when there is config
    - role: git # when there is config
    - role: vim # when there is config
    - role: n # when there is config
    - role: fzf # when there is config

  tasks:
    - name: resolv
      include_role:
        name: resolv
      when: "is_in_docker.stdout != 'bash (1, #threads: 1)'"
