---
- name: install terraform
  tags: terraform
  vars:
    asdf_user: "{{ ansible_user }}"
    asdf_group: "{{ ansible_user }}"
    asdf_plugins:
      - name: terraform
        repository:  https://github.com/asdf-community/asdf-hashicorp.git
        versions:
          - 1.3.1
        global: 1.3.1
  include_role:
    name: cimon-io.asdf
