---
- name: install docker deps
  tags:
    - docker
    - docker-compose
    - docker-compose-2
  become: yes
  apt:
    pkg:
      - curl
    state: present
    update_cache: yes
    autoclean: yes
    autoremove: yes

- name: install docker
  tags: docker
  become: yes
  shell: curl -sSL https://get.docker.com | bash
  args:
    creates: /usr/bin/docker # run if file not exist

- name: add user to docker group
  tags: docker
  become: yes
  shell: usermod -aG docker $(whoami)

- name: create docker plugin dir
  tags: docker
  file:
    path: "/home/{{ ansible_user }}/.docker/cli-plugins"
    state: directory

- name: install docker-compose
  tags: docker-compose
  get_url:
    url: https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64
    dest: "/home/{{ ansible_user }}/bin/docker-compose"
    mode: 'u=rx,g=rx,o=r'

- name: download docker compose plugin
  tags: docker-compose-2
  get_url:
    url: https://github.com/docker/compose/releases/download/v2.11.1/docker-compose-linux-x86_64
    dest: "/home/{{ ansible_user }}/.docker/cli-plugins/docker-compose"
    mode: 'u=rx,g=rx,o=r'
